apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/sync-options: Replace=true
    argocd.argoproj.io/compare-options: IgnoreExtraneous
  name: run-tests
spec:
  template:
    spec:
      containers:
      - name: run-tests
        image: curlimages/curl:latest
        command: ["/bin/sh", "-c"]
        args:
          - echo i have been run; echo when did i run; sleep 10; exit 1
      restartPolicy: Never
  backoffLimit: 0
