apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    app: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
      annotations:
        configmap-hash: {{ include "cm-change-triggers-deployment-change.configMapHash" . }}
    spec:
      containers:
        - name: my-container
          command: ["sleep","30d"]
          image: busybox:latest
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
      volumes:
        - name: config-volume
          configMap:
            name: my-config
